# env: dev
DEV:
  app:
    title: "Demo BITS Application"
    version: "1.0.0"
    

  aws:
    region: "us-east-1"

  llms:
    gemini:
      model_id: "gemini-2.5-pro" #gemini-2.5-flash
      top_k: 20
      max_workers: 8
      secret_name: "" 
      secret_key: "" 
      env: "dev"